services:
    backend:
      container_name: image-cropper-back
      build:
        context: ./backend/image
        dockerfile: ./Dockerfile
        args:
          - ENV=dev
      ports:
        - "8080:8080"

    frontend:
      container_name: image-cropper-ui
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      ports:
        - "4200:80"
      depends_on:
        - backend
          
    certbot:
      container_name: "certbot"
      image: certbot/certbot
      volumes:
        - ./certbot/conf:/etc/letsencrypt # for certboot challenges
        - ./certbot/www:/var/www/certbot # for letsencrypt certificates
      command: certonly --webroot -w /var/www/certbot -d ${DOMAIN} --force-renew --agree-tos --email ${EMAIL}
      #depends_on:
        #- fastapi
        #  - web