services:
    backend:
      container_name: image-cropper-back-dev
      build:
        context: ./backend/image
        dockerfile: ./Dockerfile
        args:
          - ENV=dev
      ports:
        - "8080:8080"

    frontend:
      container_name: image-cropper-front-dev
      build:
        context: ./frontend
        dockerfile: ./Dockerfile
      ports:
        - "4200:80"
      depends_on:
        - backend
          
