services:
    backend:
        container_name: image-cropper-back
        build:
            context: ./backend/image
            dockerfile: ./Dockerfile
        ports:
            - "8080:8080"
    frontend:
        container_name: image-cropper-ui
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
            - "4200:80"
        depends_on:
            - backend